apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:joomla| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]Joomla[/b].
    Joomla! is an open source content management system.
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]Joomla![/b]
    To access [b]Joomla[/b] use this link: [url]http://%PUBLIC_ADDRESS%[/url]
    You can access [b]MySQL[/b] using credentials:
    [b]Host:[/b] 127.0.0.1
    [b]Database:[/b] joomla
    [b]Login:[/b] joomla
    [b]Password:[/b]  $MYSQL_USER_PASSWORD$

    We recommend you to save the credentials.

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: joomla
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 3
            - name: joomla
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: joomla-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: joomla
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: joomla-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 4
            - name: joomla
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: joomla-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: joomla_mysql_$PD_RAND|default:autogen|PD rand$
        - name: joomla-persistent-storage
          persistentDisk:
            pdName: joomla_www_$PD_RAND$
      restartPolicy: "Always"
      containers:
        -
          name: mysql
          image: mysql:5
          env:
            - name: MYSQL_DATABASE
              value: joomla
            - name: MYSQL_USER
              value: joomla
            - name: MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD|default:autogen|mysql user password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql root password$
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: joomla
          image: joomla:3
          env:
            - name: JOOMLA_DB_PASSWORD
              value: $MYSQL_USER_PASSWORD$
            - name: JOOMLA_DB_HOST
              value: "127.0.0.1"
            - name: JOOMLA_DB_USER
              value: joomla
            - name: JOOMLA_DB_NAME
              value: joomla
          ports:
              - containerPort: 80
                isPublic: True
          volumeMounts:
            - mountPath: /var/www/html
              name: joomla-persistent-storage
          workingDir: /var/www/html
