apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:magento| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]Magento[/b].
    eCommerce software used to power your online store and can be downloaded for free.
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]Magento![/b]
    To access [b]Magento[/b] use this link: [url]http://%PUBLIC_ADDRESS%[/url]
    You can access [b]MySQL[/b] using credentials:
    [b]Host:[/b] 127.0.0.1
    [b]Database:[/b] magento
    [b]Login:[/b] magento
    [b]Password:[/b]  $MYSQL_USER_PASSWORD$

    We recommend you to save the credentials.

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: magento
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 5
            - name: magento
              kubes: 3
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: magento-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: magento
              kubes: 6
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: magento-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 4
            - name: magento
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: magento-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: magento_mysql_$PD_RAND|default:autogen|PD rand$
        - name: magento-persistent-storage
          persistentDisk:
            pdName: magento_www_$PD_RAND$
      restartPolicy: "Always"
      containers:
        -
          name: mysql
          image: mysql:5
          env:
            - name: MYSQL_DATABASE
              value: magento
            - name: MYSQL_USER
              value: magento
            - name: MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD|default:autogen|mysql user password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql root password$
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: magento
          image: alexcheng/magento
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    chown -R www-data:www-data /var/www/htdocs;
                    if [ ! -f /var/www/htdocs/index.php ]; then
                    cp -rp /originroot/var/www/htdocs/. /var/www/htdocs/;
                    fi
          ports:
            - containerPort: 80
              isPublic: True
          volumeMounts:
            - mountPath: /var/www/htdocs
              name: magento-persistent-storage
