apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:redmine| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]Redmine[/b].
    Redmine is a flexible project management web application written using Ruby on Rails framework
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]Redmine![/b]
    To access [b]Redmine[/b] use this link: [url]http://%PUBLIC_ADDRESS%:$REDMINE_HOST_PORT$[/url]
    You can access [b]MySQL[/b] using credentials:
    [b]Host:[/b] 127.0.0.1
    [b]Database:[/b] redmine
    [b]Login:[/b] redmine
    [b]Password:[/b] $MYSQL_USER_PASSWORD$

  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: redmine
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 3
            - name: redmine
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: redmine-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: redmine
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: redmine-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 4
            - name: redmine
              kubes: 2
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: redmine-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: redmine_mysql_$PD_RAND|default:autogen|PD rand$
        - name: redmine-persistent-storage
          persistentDisk:
            pdName: redmine_files_$PD_RAND$
      restartPolicy: "Always"
      resolve: [mysql]
      containers:
        -
          name: mysql
          image: mysql:5
          env:
            - name: MYSQL_DATABASE
              value: redmine
            - name: MYSQL_USER
              value: redmine
            - name: MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD|default:autogen|mysql user password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|mysql root password$
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: redmine
          image: redmine:3
          env:
            - name: MYSQL_PORT_3306_TCP
              value: "3306"
            - name: MYSQL_ENV_MYSQL_DATABASE
              value: redmine
            - name: MYSQL_ENV_MYSQL_USER
              value: redmine
            - name: MYSQL_ENV_MYSQL_PASSWORD
              value: $MYSQL_USER_PASSWORD$
          ports:
            - containerPort: 3000
              podPort: $REDMINE_HOST_PORT|default:3000|Enter Redmine host port$
              isPublic: True
          volumeMounts:
            - mountPath: /usr/src/redmine/files
              name: redmine-persistent-storage
          workingDir: /usr/src/redmine
