apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:whmcs| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]WHMCS[/b].
    WHMCS is the leading web hosting automation platform. Handling signups, provisioning, billing and support,
    WHMCS puts you firmly in control of your business.
    [b]Note![/b] Before proceeding with WHMCS installation, please make sure to obtain its license.
    If you have WHMCS account, please log in here : [url]https://www.whmcs.com/members/[/url]
    To register your account go here : [url]https://www.whmcs.com/order/[/url]
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]WHMCS![/b]
    Please find more information about WHMCS software on the official website [url]https://www.whmcs.com/[/url]
    To access [b]WHMCS[/b] use this link: [url]http://%PUBLIC_ADDRESS%[/url]
    Admin area is available here: [url]http://%PUBLIC_ADDRESS%/admin[/url]
    You can access [b]WHMCS[/b] using credentials:
    [b]Login:[/b] Admin
  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: WHMCS
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      baseDomain: $BASE_DOMAIN|default:hosted.cloudlinux.com|Your application base domain$
      pods:
        -
          name: $APP_NAME$
          kubeType: 0
          containers:
            - name: mysql
              kubes: 6
            - name: whmcs
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: whmcs-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      baseDomain: $BASE_DOMAIN|default:hosted.cloudlinux.com|Your application base domain$
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: mysql
              kubes: 6
            - name: whmcs
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 1
            - name: whmcs-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      baseDomain: $BASE_DOMAIN|default:hosted.cloudlinux.com|Your application base domain$
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: mysql
              kubes: 6
            - name: whmcs
              kubes: 4
          persistentDisks:
            - name: mysql-persistent-storage
              pdSize: 2
            - name: whmcs-persistent-storage
              pdSize: 2
spec:
  template:
    metadata:
      labels:
        name: $APP_NAME$
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentDisk:
            pdName: whmcs_mysql_$PD_RAND|default:autogen|PD rand$
        - name: whmcs-persistent-storage
          persistentDisk:
            pdName: whmcs_www_$PD_RAND$
      restartPolicy: "Always"
      resolve: ["mysql", "localhost"]
      containers:
        -
          name: mysql
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: $MYSQL_DATABASE|default:whmcs|MySQL database$
            - name: MYSQL_USER
              value: $MYSQL_USER|default:whmcs|MySQL user$
            - name: MYSQL_PASSWORD
              value: $MYSQL_PASSWORD|default:autogen|MySQL user password$
            - name: MYSQL_ROOT_PASSWORD
              value: $MYSQL_ROOT_PASSWORD|default:autogen|MySQL root password$
            - name: MYSQL_AUTO_MEMORY_ALLOCATE
              value: $MYSQL_AUTO_MEMORY_ALLOCATE|default:innodb|Please choose default MySQL engine "innodb" or "myisam"$
          ports:
            - containerPort: 3306
          args:
            - --sql-mode=IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        -
          name: whmcs
          image: bliss/hosted-whmcs
          env:
            - name: LICENSE
              value: $LICENSE|default:|Please enter your WHMCS license key$
            - name: PASSWORD
              value: $PASSWORD|default:|WHMCS admin password$
            - name: DOMAIN
              value: $DOMAIN|default:|WHMCS application domain$
            - name: DB_PASSWORD
              value: $MYSQL_PASSWORD$
            - name: DB_USERNAME
              value: $MYSQL_USER$
            - name: DB_NAME
              value: $MYSQL_DATABASE$
            - name: DB_HOST
              value: 127.0.0.1
            - name: SERVER_NAME
              value: whmcs.hosted.cloudlinux.com
          ports:
            - containerPort: 80
              isPublic: True
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /var/opt/persistent
              name: whmcs-persistent-storage
          workingDir: /var/opt/whmcs